
postgres_version: 9.2
postgres_repo_name: "pgdg{{ postgres_version | replace('.','') }}"
postgres_repo_url: "https://download.postgresql.org/pub/repos/yum/{{ postgres_version }}/redhat/rhel-$releasever-$basearch"
postgres_repo_key: "https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ postgres_version | replace('.','') }}"
postgres_packages:
  - postgresql{{ postgres_version | replace('.','') }}-server
postgres_service_name: "postgresql-{{ postgres_version }}"
postgres_initdb_command: "/usr/pgsql-{{ postgres_version }}/bin/postgresql{{ (postgres_version is version_compare('10', '>=')) | ternary('-','') }}{{ postgres_version | replace('.','') }}-setup initdb"
postgres_data_directory: "/var/lib/pgsql/{{ postgres_version }}/data"
postgres_config_file: "{{ postgres_data_directory }}/postgresql.conf"
postgres_hba_file: "{{ postgres_data_directory }}/pg_hba.conf"
