---

### add the creation of yum repo here

- name: copy ambari.repo
  template: 
    src: ambari.repo
    dest: /etc/yum.repos.d/ambari.repo
    mode: 0644
  when: ambarirepo|default(False)==True
    
- name: copy ambari-hdp-1.repo
  template: 
    src: ambari-hdp-1.repo
    dest: "/etc/yum.repos.d/ambari-hdp-{{hdpcount|default('1')}}.repo"
    mode: 0644
  when: hdprepo|default(False)==True
    
#- shell: yum clean all # not needed ???   
