---

- name: Add {{ user1 }} user limits
  lineinfile: 
      dest: /etc/security/limits.conf 
      line: "{{ user1 }} {{ item.limit }} {{ item.type}} {{ item.value }}"
  with_items:
    - { limit: 'soft', type: 'nofile', value: '{{ soft_no_file }}' }
    - { limit: 'hard', type: 'nofile', value: '{{ hard_no_file }}' }
    - { limit: 'soft', type: 'nproc', value: '{{ soft_nproc }}' }
    - { limit: 'hard', type: 'nproc', value: '{{ hard_nproc }}' }
