---

# not use ?

- include_tasks: ambari_server_start.yml   

- name: Set the GPL Licensed setting in Ambari
  lineinfile:
    path: /etc/ambari-server/conf/ambari.properties
    backup: no
    state: present
    regexp: "^gpl.license.accepted.*"
    line: "gpl.license.accepted={{ (accept_gpl|default(omit)|bool == true) | ternary('true', 'false') }}"
  notify: Restart ambari-server

- block:
    - name: Generate repo_version API request body from template
      template:
        src: "{{ repo_version_template | default('repo_version_template.json.j2') }}"
        dest: /tmp/repo_version_update_body.json
      become: False  
      delegate_to: localhost        

    # DOES NOT WORK
    - name: Update repo_version model to set ambari_managed_repositories=false
      uri:
        url: "http://{{ ansible_fqdn }}:8080/api/v1/stacks/HDP/versions/{{ hdp_minor_version }}/repository_versions/1"
        method: PUT
        force_basic_auth: yes
        user: "{{ ambari_admin_user }}"
        password: "{{ ambari_admin_password }}"
        headers:
          "X-Requested-By": "ambari"
          "Content-type": "Application/json"
        body: "{{ lookup('file', '/tmp/repo_version_update_body.json')|to_json }}"
        status_code: 200
  #when: not (ambari_managed_repositories|default(True))

- meta: flush_handlers

