---

- name: Delete {{filename1}}.{{ext}}
  file: 
    path: './{{item}}'
    state: absent
  delegate_to: localhost # ansible
  run_once: true
  with_items:
     - '{{filename1}}.{{ext}}'
     - '{{filename1}}2.{{ext}}'
  
  
- name: Delete {{tmp_folder_win}}
  win_file: 
     path: "{{tmp_folder_win}}"
     state: absent
  become: true
  ignore_errors: true  

- set_fact: log_file_win="log_{{inventory_hostname}}_{{lookup('pipe','date +%Y%m%d-%H%M')}}.{{ext}}"
- set_fact: log_file_tower_win="tower_{{inventory_hostname}}_{{lookup('pipe','date +%Y%m%d-%H%M')}}.{{ext}}"
- set_fact: path_log_win="{{tmp_folder_win}}\{{log_file_win}}"

- name: Create {{tmp_folder_win}} folder
  win_file: path={{tmp_folder_win}} state=directory
  
- name: Create {{path_log_win}} 
  win_file: path="{{path_log_win}}" state=touch 
  
- name: "check size of {{path_log_win}}"
  win_stat: path={{path_log_win}}  
  register: x
  failed_when: x.stat.size!=0
  
- shell: |
         echo >> {{path_log_win}}  # first line
  when: lines|default(False)==True       
  